version: "3.8"

networks:
  urlShortener-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: ${mongo_container_name}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - urlShortener-network

  redis:
    image: redis:latest
    container_name: ${redis_container_name}
    restart: always
    command: redis-server --requirepass ${SPRING_DATA_REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - urlShortener-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE:${JAR_FILE}
    container_name: ${spring_container_name}
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
    volumes:
      - spring-log-data:/app/logs
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - urlShortener-network

volumes:
  mongodb-data:
  redis-data:
  spring-log-data: