package ch.hos6.openweb.urlShortener.domain.entity;

import ch.hos6.openweb.urlShortener.security.CustomUserDetails;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * User entity for authentication and authorization.
 * This entity is stored in the 'users' collection in MongoDB.
 *
 * @author Toubia Oussama
 */
@Data
@Document(collection = "users")
public class User extends CustomUserDetails implements UserDetails {
    /**
     * Unique identifier of the user.
     * This field is automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * Username of the user.
     * This field is used for authentication.
     */
    @Indexed(unique = true)
    private String username;

    /**
     * Password of the user.
     * This field is used for authentication.
     */
    private String password;


}
